### ISSUE TITLE
Suggestion Based on Keepachangelog

### ISSUE THREAD

**Issue by weallwegot** [MartinSeeler/auto-changelog-hook#4]
Glad you added the standard proposed in keepachangelog.com i was literally just thinking about this. but the project could still be valuable if it detected git tag and prevents a commit if there is no update to changelog file. instead of trying to populate the changelog just making sure it gets updated with new releases? 

Any thoughts on this?

**Comment by MartinSeeler** [comment]
Thanks for your thoughts! The script was intended for all those "throw it in and now we have a Changelog" people. I would suggest to keep a real Changelog file. But yes, I think this could be useful for a few people. It may be possible by checking the changed lines length combined with the tag check. On the other side, this seems to be an edge case, which is not so often used as this script.

So my opinion is, that you should add this checks and use the customized version if you want to 👍
